name: ml-codes

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - python-dotenv
  - autopep8
  - ipykernel
  - pylint
  - pip
  - pip:
      - tqdm